journey
    title High-Level App User Journey
    section Start new Chat - "New" page
      Write first message: 5
      Submit first message: 5
    section Continue chat - "Chat" page
      See 1st user message and system message: 5
      Continue chatting (more messages): 5
      Rename, Star, and Delete chat: 5
    section Create new Project - "Projects" page
      Name and give description: 5:
      Click "Create" (redirects to Project page): 5
    section "Project" page
      Edit project details (name, description): 5
      Star project: 5
      Start new Chat in Project (submit 1st message): 5
      Continue chat - "Chat" page: 5
    section "Settings" page
      Open Navigaion Drawer: 5
      Select Settings: 5
      Access Settings tabs (Profile, Appearance, etc.): 5
